packages:
  - plugins/*
  - tooling/*
allowBuilds:
  '@google/genai': false
  esbuild: false
  koffi: false
  msgpackr-extract: false
  protobufjs: false
minimumReleaseAgeExclude:
  - '@earendil-works/pi-agent-core@0.86.0'
  - '@earendil-works/pi-ai@0.86.0'
  - '@earendil-works/pi-coding-agent@0.86.0'
  - '@earendil-works/pi-tui@0.86.0'
  - '@effect/platform-node-shared@4.0.0-beta.103'
  - '@effect/platform-node@4.0.0-beta.103'
  - 'effect@4.0.0-beta.103'
  - 'tsdown@0.22.14'
  - '@earendil-works/chord@0.86.0'
  - '@earendil-works/pi-telemetry@0.86.0'
