name: Zizmor
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  zizmor:
    name: GH Actions Security Analysis with zizmor
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - name: Run zizmor
        run: nix develop --command zizmor --format=github .github/workflows
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
